//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18052
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplicationJanvier.ServiceReferencePays {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pays", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Pays : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Nom {
            get {
                return this.NomField;
            }
            set {
                if ((object.ReferenceEquals(this.NomField, value) != true)) {
                    this.NomField = value;
                    this.RaisePropertyChanged("Nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferencePays.WebServicePaysSoap")]
    public interface WebServicePaysSoap {
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément ListerPaysResult de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListerPays", ReplyAction="*")]
        WindowsFormsApplicationJanvier.ServiceReferencePays.ListerPaysResponse ListerPays(WindowsFormsApplicationJanvier.ServiceReferencePays.ListerPaysRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListerPays", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApplicationJanvier.ServiceReferencePays.ListerPaysResponse> ListerPaysAsync(WindowsFormsApplicationJanvier.ServiceReferencePays.ListerPaysRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément pi de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EnregistrerPays", ReplyAction="*")]
        WindowsFormsApplicationJanvier.ServiceReferencePays.EnregistrerPaysResponse EnregistrerPays(WindowsFormsApplicationJanvier.ServiceReferencePays.EnregistrerPaysRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EnregistrerPays", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApplicationJanvier.ServiceReferencePays.EnregistrerPaysResponse> EnregistrerPaysAsync(WindowsFormsApplicationJanvier.ServiceReferencePays.EnregistrerPaysRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément nom de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestEnregistrerPays", ReplyAction="*")]
        WindowsFormsApplicationJanvier.ServiceReferencePays.TestEnregistrerPaysResponse TestEnregistrerPays(WindowsFormsApplicationJanvier.ServiceReferencePays.TestEnregistrerPaysRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestEnregistrerPays", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApplicationJanvier.ServiceReferencePays.TestEnregistrerPaysResponse> TestEnregistrerPaysAsync(WindowsFormsApplicationJanvier.ServiceReferencePays.TestEnregistrerPaysRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListerPaysRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListerPays", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplicationJanvier.ServiceReferencePays.ListerPaysRequestBody Body;
        
        public ListerPaysRequest() {
        }
        
        public ListerPaysRequest(WindowsFormsApplicationJanvier.ServiceReferencePays.ListerPaysRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListerPaysRequestBody {
        
        public ListerPaysRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListerPaysResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListerPaysResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplicationJanvier.ServiceReferencePays.ListerPaysResponseBody Body;
        
        public ListerPaysResponse() {
        }
        
        public ListerPaysResponse(WindowsFormsApplicationJanvier.ServiceReferencePays.ListerPaysResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListerPaysResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<WindowsFormsApplicationJanvier.ServiceReferencePays.Pays> ListerPaysResult;
        
        public ListerPaysResponseBody() {
        }
        
        public ListerPaysResponseBody(System.Collections.Generic.List<WindowsFormsApplicationJanvier.ServiceReferencePays.Pays> ListerPaysResult) {
            this.ListerPaysResult = ListerPaysResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnregistrerPaysRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnregistrerPays", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplicationJanvier.ServiceReferencePays.EnregistrerPaysRequestBody Body;
        
        public EnregistrerPaysRequest() {
        }
        
        public EnregistrerPaysRequest(WindowsFormsApplicationJanvier.ServiceReferencePays.EnregistrerPaysRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EnregistrerPaysRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsApplicationJanvier.ServiceReferencePays.Pays pi;
        
        public EnregistrerPaysRequestBody() {
        }
        
        public EnregistrerPaysRequestBody(WindowsFormsApplicationJanvier.ServiceReferencePays.Pays pi) {
            this.pi = pi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnregistrerPaysResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnregistrerPaysResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplicationJanvier.ServiceReferencePays.EnregistrerPaysResponseBody Body;
        
        public EnregistrerPaysResponse() {
        }
        
        public EnregistrerPaysResponse(WindowsFormsApplicationJanvier.ServiceReferencePays.EnregistrerPaysResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EnregistrerPaysResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long EnregistrerPaysResult;
        
        public EnregistrerPaysResponseBody() {
        }
        
        public EnregistrerPaysResponseBody(long EnregistrerPaysResult) {
            this.EnregistrerPaysResult = EnregistrerPaysResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestEnregistrerPaysRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestEnregistrerPays", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplicationJanvier.ServiceReferencePays.TestEnregistrerPaysRequestBody Body;
        
        public TestEnregistrerPaysRequest() {
        }
        
        public TestEnregistrerPaysRequest(WindowsFormsApplicationJanvier.ServiceReferencePays.TestEnregistrerPaysRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TestEnregistrerPaysRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nom;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string code;
        
        public TestEnregistrerPaysRequestBody() {
        }
        
        public TestEnregistrerPaysRequestBody(string nom, string code) {
            this.nom = nom;
            this.code = code;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestEnregistrerPaysResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestEnregistrerPaysResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplicationJanvier.ServiceReferencePays.TestEnregistrerPaysResponseBody Body;
        
        public TestEnregistrerPaysResponse() {
        }
        
        public TestEnregistrerPaysResponse(WindowsFormsApplicationJanvier.ServiceReferencePays.TestEnregistrerPaysResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TestEnregistrerPaysResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long TestEnregistrerPaysResult;
        
        public TestEnregistrerPaysResponseBody() {
        }
        
        public TestEnregistrerPaysResponseBody(long TestEnregistrerPaysResult) {
            this.TestEnregistrerPaysResult = TestEnregistrerPaysResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServicePaysSoapChannel : WindowsFormsApplicationJanvier.ServiceReferencePays.WebServicePaysSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServicePaysSoapClient : System.ServiceModel.ClientBase<WindowsFormsApplicationJanvier.ServiceReferencePays.WebServicePaysSoap>, WindowsFormsApplicationJanvier.ServiceReferencePays.WebServicePaysSoap {
        
        public WebServicePaysSoapClient() {
        }
        
        public WebServicePaysSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServicePaysSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServicePaysSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServicePaysSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplicationJanvier.ServiceReferencePays.ListerPaysResponse WindowsFormsApplicationJanvier.ServiceReferencePays.WebServicePaysSoap.ListerPays(WindowsFormsApplicationJanvier.ServiceReferencePays.ListerPaysRequest request) {
            return base.Channel.ListerPays(request);
        }
        
        public System.Collections.Generic.List<WindowsFormsApplicationJanvier.ServiceReferencePays.Pays> ListerPays() {
            WindowsFormsApplicationJanvier.ServiceReferencePays.ListerPaysRequest inValue = new WindowsFormsApplicationJanvier.ServiceReferencePays.ListerPaysRequest();
            inValue.Body = new WindowsFormsApplicationJanvier.ServiceReferencePays.ListerPaysRequestBody();
            WindowsFormsApplicationJanvier.ServiceReferencePays.ListerPaysResponse retVal = ((WindowsFormsApplicationJanvier.ServiceReferencePays.WebServicePaysSoap)(this)).ListerPays(inValue);
            return retVal.Body.ListerPaysResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApplicationJanvier.ServiceReferencePays.ListerPaysResponse> WindowsFormsApplicationJanvier.ServiceReferencePays.WebServicePaysSoap.ListerPaysAsync(WindowsFormsApplicationJanvier.ServiceReferencePays.ListerPaysRequest request) {
            return base.Channel.ListerPaysAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplicationJanvier.ServiceReferencePays.ListerPaysResponse> ListerPaysAsync() {
            WindowsFormsApplicationJanvier.ServiceReferencePays.ListerPaysRequest inValue = new WindowsFormsApplicationJanvier.ServiceReferencePays.ListerPaysRequest();
            inValue.Body = new WindowsFormsApplicationJanvier.ServiceReferencePays.ListerPaysRequestBody();
            return ((WindowsFormsApplicationJanvier.ServiceReferencePays.WebServicePaysSoap)(this)).ListerPaysAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplicationJanvier.ServiceReferencePays.EnregistrerPaysResponse WindowsFormsApplicationJanvier.ServiceReferencePays.WebServicePaysSoap.EnregistrerPays(WindowsFormsApplicationJanvier.ServiceReferencePays.EnregistrerPaysRequest request) {
            return base.Channel.EnregistrerPays(request);
        }
        
        public long EnregistrerPays(WindowsFormsApplicationJanvier.ServiceReferencePays.Pays pi) {
            WindowsFormsApplicationJanvier.ServiceReferencePays.EnregistrerPaysRequest inValue = new WindowsFormsApplicationJanvier.ServiceReferencePays.EnregistrerPaysRequest();
            inValue.Body = new WindowsFormsApplicationJanvier.ServiceReferencePays.EnregistrerPaysRequestBody();
            inValue.Body.pi = pi;
            WindowsFormsApplicationJanvier.ServiceReferencePays.EnregistrerPaysResponse retVal = ((WindowsFormsApplicationJanvier.ServiceReferencePays.WebServicePaysSoap)(this)).EnregistrerPays(inValue);
            return retVal.Body.EnregistrerPaysResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApplicationJanvier.ServiceReferencePays.EnregistrerPaysResponse> WindowsFormsApplicationJanvier.ServiceReferencePays.WebServicePaysSoap.EnregistrerPaysAsync(WindowsFormsApplicationJanvier.ServiceReferencePays.EnregistrerPaysRequest request) {
            return base.Channel.EnregistrerPaysAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplicationJanvier.ServiceReferencePays.EnregistrerPaysResponse> EnregistrerPaysAsync(WindowsFormsApplicationJanvier.ServiceReferencePays.Pays pi) {
            WindowsFormsApplicationJanvier.ServiceReferencePays.EnregistrerPaysRequest inValue = new WindowsFormsApplicationJanvier.ServiceReferencePays.EnregistrerPaysRequest();
            inValue.Body = new WindowsFormsApplicationJanvier.ServiceReferencePays.EnregistrerPaysRequestBody();
            inValue.Body.pi = pi;
            return ((WindowsFormsApplicationJanvier.ServiceReferencePays.WebServicePaysSoap)(this)).EnregistrerPaysAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplicationJanvier.ServiceReferencePays.TestEnregistrerPaysResponse WindowsFormsApplicationJanvier.ServiceReferencePays.WebServicePaysSoap.TestEnregistrerPays(WindowsFormsApplicationJanvier.ServiceReferencePays.TestEnregistrerPaysRequest request) {
            return base.Channel.TestEnregistrerPays(request);
        }
        
        public long TestEnregistrerPays(string nom, string code) {
            WindowsFormsApplicationJanvier.ServiceReferencePays.TestEnregistrerPaysRequest inValue = new WindowsFormsApplicationJanvier.ServiceReferencePays.TestEnregistrerPaysRequest();
            inValue.Body = new WindowsFormsApplicationJanvier.ServiceReferencePays.TestEnregistrerPaysRequestBody();
            inValue.Body.nom = nom;
            inValue.Body.code = code;
            WindowsFormsApplicationJanvier.ServiceReferencePays.TestEnregistrerPaysResponse retVal = ((WindowsFormsApplicationJanvier.ServiceReferencePays.WebServicePaysSoap)(this)).TestEnregistrerPays(inValue);
            return retVal.Body.TestEnregistrerPaysResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApplicationJanvier.ServiceReferencePays.TestEnregistrerPaysResponse> WindowsFormsApplicationJanvier.ServiceReferencePays.WebServicePaysSoap.TestEnregistrerPaysAsync(WindowsFormsApplicationJanvier.ServiceReferencePays.TestEnregistrerPaysRequest request) {
            return base.Channel.TestEnregistrerPaysAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplicationJanvier.ServiceReferencePays.TestEnregistrerPaysResponse> TestEnregistrerPaysAsync(string nom, string code) {
            WindowsFormsApplicationJanvier.ServiceReferencePays.TestEnregistrerPaysRequest inValue = new WindowsFormsApplicationJanvier.ServiceReferencePays.TestEnregistrerPaysRequest();
            inValue.Body = new WindowsFormsApplicationJanvier.ServiceReferencePays.TestEnregistrerPaysRequestBody();
            inValue.Body.nom = nom;
            inValue.Body.code = code;
            return ((WindowsFormsApplicationJanvier.ServiceReferencePays.WebServicePaysSoap)(this)).TestEnregistrerPaysAsync(inValue);
        }
    }
}
